# Generated by Django 4.2.7 on 2023-12-18 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Amazon', '0004_alter_category_category_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(default='', max_length=200, null=True)),
                ('mobile', models.BigIntegerField()),
                ('price', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('status', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Amazon.registrations')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Amazon.product')),
            ],
        ),
    ]
