# Generated by Django 4.2.6 on 2023-12-22 17:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Amazon", "0006_best_of_fashion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="best_of_fashion",
            name="product_image",
            field=models.ImageField(upload_to="upload/Best_of_Fashion/"),
        ),
    ]
