# Generated by Django 4.2.6 on 2023-12-22 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("Amazon", "0007_alter_best_of_fashion_product_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Best_of_Fitness",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product_image",
                    models.ImageField(upload_to="upload/Best_of_Fitness/"),
                ),
                (
                    "product_name",
                    models.CharField(default="", max_length=100, null=True),
                ),
                ("product_price", models.BigIntegerField(default=1)),
                (
                    "product_description",
                    models.TextField(blank=True, max_length=200, null=True),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Amazon.category",
                    ),
                ),
            ],
        ),
    ]
